@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package liedge.bannercapes.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;