@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package liedge.bannercapes.integration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;