@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package liedge.bannercapes.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;