@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package liedge.bannercapes.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;